### ISSUE TITLE
Already a nexus.io on the internet

### ISSUE THREAD

**Issue by NealHelman** [ThibaultFriedrich/nexus.io#1]
How rude is it that you're using a registered domain name, nexus.io?

**Comment by Jugalug123** [comment]
Yeah the real Nexus.io is nowhere to be seen if you search through Microsoft edge.
Something fishy is going on here, it's almost like it's a designed attack on Nexus.io why else would it be removed from Microsoft Edge.

**Comment by TrickCoin** [comment]
This is not right...you are not nexus.io. That domain is owned by Nexus Blockchain. You are falsely advertising by continuing to call yourself Nexus.io

**Comment by amused-guy** [comment]
This is the new Nexus Community in a nutshell. Big words but too stupid to see that this repository was created in 2016 and is dead since then.. waaay before nexusearth was  renamed to nexus.io. Maybe you are getting the copyright issue. Just lol...
Commits on Jul 24, 2016

    [Initial commit](https://github.com/nexus-iot/nexus.io/commit/2450aa8154500a91e4076709f71cc41cc44f9780)
    Thibault Friedrich authored and Thibault Friedrich committed on 24 Jul 2016

**Comment by friedrith** [comment]
I really don't know what happened with you guy. I guess Microsoft Edge just referenced github repos somewhere in your search bar but I really don't care.  @amused-guy showed the good point. 
Best regards,
